//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greer_P2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory
    {
        public string fldProductSKU { get; set; }
        public Nullable<int> fldCatagoryID { get; set; }
        public string fldProductName { get; set; }
        public string fldProductDescription { get; set; }
        public Nullable<decimal> fldProductPrice { get; set; }
        public string fldProductImageFile { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
    }
}
